area/ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.changeset/**'
          - 'turbo.json'

area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'assets/**'

area/typescript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ts'
          - '**/*.tsx'

area/javascript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.js'
          - '**/*.cjs'
          - '**/*.mjs'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'packages/*/package.json'
