export { AsyncAPIDocument as AsyncAPIDocumentV2 } from './asyncapi';
export { Contact as ContactV2 } from './contact';
export { Info as InfoV2 } from './info';
export { License as LicenseV2 } from './license';
export { Bindings as BindingsV2, Binding as BindingV2 } from './mixins/bindings';
export { Extensions as ExtensionsV2, Extension as ExtensionV2 } from './mixins/extensions';
export { ExternalDocumentation as ExternalDocumentationV2 } from './mixins/external-docs';
export { Tags as TagsV2, Tag as TagV2 } from './mixins/tags';
export { Server as ServerV2 } from './server';
export { Servers as ServersV2 } from './servers';
export { SecurityScheme as SecuritySchemeV2 } from './security-scheme';
export { SecuritySchemes as SecuritySchemesV2 } from './security-schemes';
export { ServerVariable as ServerVariableV2 } from './server-variable';
export { ServerVariables as ServerVariablesV2 } from './server-variables';
