export { AsyncAPIDocument as AsyncAPIDocumentV3 } from './asyncapi';
export { Contact as ContactV3 } from './contact';
export { Info as InfoV3 } from './info';
export { License as LicenseV3 } from './license';
export { Bindings as BindingsV3, Binding as BindingV3 } from './mixins/bindings';
export { Extensions as ExtensionsV3, Extension as ExtensionV3 } from './mixins/extensions';
export { ExternalDocumentation as ExternalDocumentationV3 } from './mixins/external-docs';
export { Tags as TagsV3, Tag as TagV3 } from './mixins/tags';
export { Server as ServerV3 } from './server';
export { Servers as ServersV3 } from './servers';
export { SecurityScheme as SecuritySchemeV3 } from './security-scheme';
export { SecuritySchemes as SecuritySchemesV3 } from './security-schemes';
export { ServerVariable as ServerVariableV3 } from './server-variable';
export { ServerVariables as ServerVariablesV3 } from './server-variables';
