name: Pull request testing

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Regenerate types to make sure nothing is broken
        run: npm run types
      - name: Regenerate docs to make sure jsdoc are not broken
        run: npm run docs
